Level 3/store/config/routes.rb
Rails.application.routes.draw do
  root "company#index"

  post "/companies", to: "company#index"
  get "/company/:id", to: "company#show", as: 'company'
  get "/company/new", to: "company#new", as: 'new_company'
  post "/company(.:format)", to: "company#create", as: 'company_create'
  get "/company/:id/edit", to: "company#edit", as: 'edit_company'
  patch "/company/:id(.:format)", to: "company#update"
  delete "/company/:id(.:format)", to: "company#destroy"
  
  post "/books", to: "book#index"
  get "/book/:id", to: "book#show", as: 'book'
  get "/book/new/:company_id", to: "book#new", as: 'new_book'
  post "/book/:company_id(.:format)", to: "book#create", as: 'book_create'
  get "/book/:id/edit", to: "book#edit", as: 'edit_book'
  patch "/book/:id(.:format)", to: "book#update"
  delete "/book/:id(.:format)", to: "book#destroy"
  
  post "/games", to: "game#index"
  get "/game/:id", to: "game#show", as: 'game'
  get "/game/new/:company_id", to: "game#new", as: 'new_game'
  post "/game/:company_id(.:format)", to: "game#create", as: 'game_create'
  get "/game/:id/edit", to: "game#edit", as: 'edit_game'
  patch "/game/:id(.:format)", to: "game#update"
  delete "/game/:id(.:format)", to: "game#destroy"
end

Level 3/store/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :company
  validates :author, presence: true, length: { minimum: 3, maximum:30 }
  validates :description, presence: true, length: {maximum:250 }
  validates :name, presence: true
  validates :price, presence: true, numericality: true
end

Level 3/store/app/models/company.rb
class Company < ApplicationRecord
  has_many :book
  has_many :game
  validates :name, presence: true, length: { minimum: 10 }
end

Level 3/store/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :company
  validates :description, presence: true, length: {maximum:250 }
  validates :name, presence: true
  validates :price, presence: true, numericality: true
end

Level 3/store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Level 3/store/app/controllers/book_controller.rb
class BookController < ApplicationController
  #  before_action :get_company
    def index
    @book = Book.all
  end
  
  def new
    @company = Company.find(params[:company_id])
    @book = Book.new
    @book.company_id=@company.id
  end
  
  def show
    @book = Book.find(params[:id])
  end

  def create
    @company = Company.find(params[:company_id])
    @book = @company.book.create(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to  company_path(@company), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @company = Company.find(@book.company_id)
    if @book.update(book_params)
      redirect_to company_path(@company)
    else
      render :edit
    end
  end
  
  def destroy
    @company = Company.find(params[:company_id])
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to company_path(@company)
  end
  
 

  private
  def book_params
    params.require(:book).permit(:id, :name, :author, :price,:editor,:description,:company_id)
  end
  
  #  def get_company
  #    @company = Company.find(params[:company_id])
  #  end
end

Level 3/store/app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def index
    @company = Company.all
  end

  def new
    @company = Company.new
  end
  
  def show
    @company = Company.find(params[:id])
  end

  def create
    @company = Company.create(company_params)

    if @company.save
      redirect_to @company
    else
      render :new
    end
  end
  
  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to @company
    else
      render :edit
    end
  end
  
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    redirect_to root_path
  end
  
  private
  def company_params
    params.require(:company).permit(:id,:name)
  end
end

Level 3/store/app/controllers/game_controller.rb
class GameController < ApplicationController
    #  before_action :get_company
    def index
    @game = Game.all
  end
  
  def new
    @company = Company.find(params[:company_id])
    @game = Game.new
    @game.company_id=@company.id
  end
  
  def show
    @game = Game.find(params[:id])
  end

  def create
    @company = Company.find(params[:company_id])
    @game = @company.game.create(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to  company_path(@company), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    @company = Company.find(@game.company_id)
    if @game.update(game_params)
      redirect_to company_path(@company)
    else
      render :edit
    end
  end
  
  def destroy
    @company = Company.find(params[:company_id])
    @game = Game.find(params[:id])
    @game.destroy

    redirect_to company_path(@company)
  end
  
 

  private
  def game_params
    params.require(:game).permit(:id, :name, :price,:platform,:description,:company_id)
  end

end

Level 3/store/app/helpers/application_helper.rb
module ApplicationHelper
end

Level 3/store/app/helpers/book_helper.rb
module BookHelper
end

Level 3/store/app/helpers/company_helper.rb
module CompanyHelper
end

Level 3/store/app/helpers/game_helper.rb
module GameHelper
end

Level 3/store/app/views/book/_form.html.erb
<%= form_with model: book do |form| %>


  <div>
      <%= form.label :name %><br>
      <%= form.text_field  :name %><br>
      <% book.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>
<div>
      <%= form.label :author %><br>
      <%= form.text_field  :author %><br>
      <% book.errors.full_messages_for(:author).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :price %><br>
      <%= form.text_field  :price %><br>
      <% book.errors.full_messages_for(:price).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :editor %><br>
      <%= form.text_field  :editor %><br>
      <% book.errors.full_messages_for(:editor).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :description %><br>
      <%= form.text_area :description %><br>
      <% book.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
      <%= form.submit %>
  </div>
<% end %>

Level 3/store/app/views/book/edit.html.erb
<h1>Edit Book</h1>

<%= form_with model: @book, url: {action: :update}  do |form| %>


  <div>
      <%= form.label :name %><br>
      <%= form.text_field  :name %><br>
      <% @book.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>
<div>
      <%= form.label :author %><br>
      <%= form.text_field  :author %><br>
      <% @book.errors.full_messages_for(:author).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :price %><br>
      <%= form.text_field  :price %><br>
      <% @book.errors.full_messages_for(:price).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :editor %><br>
      <%= form.text_field  :editor %><br>
      <% @book.errors.full_messages_for(:editor).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :description %><br>
      <%= form.text_area :description %><br>
      <% @book.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
      <%= form.submit %>
  </div>
<% end %>

Level 3/store/app/views/book/index.html.erb
<h1>Books</h1>

<ul>
  <% @book.each do |book| %>
    <li>
     <%= link_to book.name, book %>
    </li>
  <% end %>
    
</ul>

Level 3/store/app/views/book/new.html.erb
<h1>New Book</h1>

<%= form_for @book, url: {action: :create}  do |form| %>


  <div>
      <%= form.label :name %><br>
      <%= form.text_field  :name %><br>
      <% @book.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>
<div>
      <%= form.label :author %><br>
      <%= form.text_field  :author %><br>
      <% @book.errors.full_messages_for(:author).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :price %><br>
      <%= form.text_field  :price %><br>
      <% @book.errors.full_messages_for(:price).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :editor %><br>
      <%= form.text_field  :editor %><br>
      <% @book.errors.full_messages_for(:editor).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :description %><br>
      <%= form.text_area :description %><br>
      <% @book.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
      <%= form.submit %>
  </div>
<% end %>

Level 3/store/app/views/book/show.html.erb
<h1>Id: <%= @book.id %></h1>

<p>Name: <%= @book.name %></p>

<p>Author: <%= @book.author %></p>

<p>Price: <%= @book.price %></p>

<p>Editor: <%= @book.editor %></p>

<p>Description: <%= @book.description %></p>

<ul>
  <li><%= link_to "Edit", edit_book_path(@book) %></li>
  <li><%= link_to "Destroy", book_path(@book),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

<

<%= link_to "New Book", new_book_path(company_id: @book.company_id)%>

Level 3/store/app/views/company/_form.html.erb
<%= form_with model: company do |form| %>


  <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %><br>
      <% @company.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
      <%= form.submit %>
  </div>
<% end %>

Level 3/store/app/views/company/edit.html.erb
<h1>Edit Company</h1>

<%= form_with model: @company do |form| %>


  <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %><br>
      <% @company.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
      <%= form.submit %>
  </div>
<% end %>

Level 3/store/app/views/company/index.html.erb
<h1>Companies</h1>

<ul>
  <% @company.each do |company| %>
    <li>
     <%= link_to company.name, company %>
    </li>
  <% end %>
    
</ul>

<%= link_to "New Company", new_company_path %>

Level 3/store/app/views/company/new.html.erb
<h1>New Company</h1>

<%= form_for @company, url: {action: :create} do  |form| %>


  <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %><br>
      <% @company.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
      <%= form.submit %>
  </div>
<% end %>

Level 3/store/app/views/company/show.html.erb
<h1><%= @company.id %></h1>

<p><%= @company.name %></p>

<ul>
    <li><%= link_to "Edit", edit_company_path(@company) %></li>
    <li><%= link_to "Destroy", company_path(@company),
          method: :delete,
          data: { confirm: "Are you sure?" } %></li>
</ul>

<br/>
<div class="container">   
    <h3>BOOK LIST</h3>   

    <div>   
        <%= link_to "New Book", new_book_path(company_id: @company.id)%>  
    </div>   
    <br>   
    <table border="2">   
        <thead>   
            <tr>   
                <th>Name</th>   
                <th>Author</th>   
                <th>Price</th> 
                <th>Editor</th>
                <th>Description</th>
                <th>Actions</th>   
            </tr>   
        </thead>   
        <tbody>   
            <% @company.book.each do |book|  %>   
              <tr>   
                  <td><%= book.name %></td>   
                  <td><%= book.author %></td>   
                  <td><%= book.price %></td>   
                  <td><%= book.editor %></td>   
                  <td><%= truncate(book.description, :length => 75) %></td>   
          <div>   
              <td>   
                  <%= link_to 'Show', book_path(book) %>  
                  <%= link_to "Edit", edit_book_path(book) %>
                  <%= link_to "Destroy", book_path(book),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %>
          </div>   
          </td>   
          </tr>   
        <% end %>   
        </tbody>   
    </table>   
</div>   

<br/>

<div class="container">   
    <h3>GAME LIST</h3>   

    <div>   
        <%= link_to "New Game", new_game_path(company_id: @company.id)%>  
    </div>   
    <br>   
    <table border="2">   
        <thead>   
            <tr>   
                <th>Name</th>     
                <th>Price</th> 
                <th>Platform</th>
                <th>Description</th>
                <th>Actions</th>   
            </tr>   
        </thead>   
        <tbody>   
            <% @company.game.each do |game|  %>   
              <tr>   
                  <td><%= game.name %></td>     
                  <td><%= game.price %></td>   
                  <td><%= game.platform %></td>   
                  <td><%= truncate(game.description, :length => 75) %></td>   
          <div>   
              <td>   
                  <%= link_to 'Show', game_path(game) %>  
                  <%= link_to "Edit", edit_game_path(game) %>
                  <%= link_to "Destroy", game_path(game),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %>
          </div>   
          </td>   
          </tr>   
        <% end %>   
        </tbody>   
    </table>   
</div>   

Level 3/store/app/views/game/edit.html.erb
<h1>Edit Game</h1>

<%= form_with model: @game  do |form| %>


  <div>
      <%= form.label :name %><br>
      <%= form.text_field  :name %><br>
      <% @game.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>


<div>
      <%= form.label :price %><br>
      <%= form.text_field  :price %><br>
      <% @game.errors.full_messages_for(:price).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :platform %><br>
      <%= form.text_field  :platform %><br>
      <% @game.errors.full_messages_for(:platform).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :description %><br>
      <%= form.text_area :description %><br>
      <% @game.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
      <%= form.submit %>
  </div>
<% end %>

Level 3/store/app/views/game/index.html.erb
<h1>Games</h1>

<ul>
  <% @game.each do |game| %>
    <li>
     <%= link_to game.name, game %>
    </li>
  <% end %>
    
</ul>

Level 3/store/app/views/game/new.html.erb
<h1>New Game</h1>

<%= form_for @game, url: {action: :create}  do |form| %>

  <div>
      <%= form.label :name %><br>
      <%= form.text_field  :name %><br>
      <% @game.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>


<div>
      <%= form.label :price %><br>
      <%= form.text_field  :price %><br>
      <% @game.errors.full_messages_for(:price).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :platform %><br>
      <%= form.text_field  :platform %><br>
      <% @game.errors.full_messages_for(:platform).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

<div>
      <%= form.label :description %><br>
      <%= form.text_area :description %><br>
      <% @game.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
      <%= form.submit %>
  </div>
<% end %>

Level 3/store/app/views/game/show.html.erb
<h1>Id: <%= @game.id %></h1>

<p>Name: <%= @game.name %></p>


<p>Price: <%= @game.price %></p>

<p>Editor: <%= @game.platform %></p>

<p>Description: <%= @game.description %></p>

<ul>
  <li><%= link_to "Edit", edit_game_path(@game) %></li>
  <li><%= link_to "Destroy", game_path(@game),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

<

<%= link_to "New Game", new_game_path(company_id: @game.company_id)%>

Level 3/store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>